### PR TITLE
Translations fix

### LINKED ISSUE #37: Fix translations for All supported languages

### PR DESCRIPTION
**Pull request by Oleg-designer**
Fix #37

### CODE REVIEW

File: HanoiTowers/client/languages/en.ts [hunk 1]
```diff
@@ -199,187 +202,187 @@
     <message>
         <location filename="../Help.qml" line="48"/>
         <source>Your task is to transfer discs of different sizesfrom the left tower to third tower.You can only transfer the top drive of the tower.You can not transfer several disks at once and put larger disks on small disks.</source>
-        <translation type="unfinished"></translation>
+        <translation>Your task is to transfer discs of different sizesfrom the left tower to third tower.You can only transfer the top drive of the tower.You can not transfer several disks at once and put larger disks on small disks.</translation>
```
Comment (EndrII) [inline HanoiTowers/client/languages/en.ts:205]: sizesfrom - separate this.
and two "tower.You"

File: HanoiTowers/client/languages/en.ts [hunk 2]
```diff
@@ -199,187 +202,187 @@
...
         <location filename="../QMLLoginView/LoginView/src/LoginViewModule/LoginView.qml" line="129"/>
         <source>EMail</source>
-        <translation type="unfinished"></translation>
+        <translation>EMail</translation>
     </message>
     <message>
         <location filename="../QMLLoginView/LoginView/src/LoginViewModule/LoginView.qml" line="133"/>
         <source>Empty or incorrect email address. Please enter yuor name.</source>
-        <translation type="unfinished"></translation>
+        <translation>Empty or incorrect email address. Please enter your name.</translation>
```
Comment (EndrII) [inline HanoiTowers/client/languages/en.ts:264]: change please name to email

File: HanoiTowers/client/languages/en.ts [hunk 3]
```diff
@@ -199,187 +202,187 @@
...
         <location filename="../QMLLoginView/LoginView/src/LoginViewModule/LoginView.qml" line="148"/>
         <source>Nickname</source>
-        <translation type="unfinished"></translation>
+        <translation>Nickname</translation>
     </message>
     <message>
         <location filename="../QMLLoginView/LoginView/src/LoginViewModule/LoginView.qml" line="152"/>
         <source>Empty or incorrect Nickname. Please enter yuor name.</source>
-        <translation type="unfinished"></translation>
+        <translation>Empty or incorrect Nickname. Please enter your name.</translation>
```
Comment (EndrII) [inline HanoiTowers/client/languages/en.ts:274]: please change name to the Nickname

File: HanoiTowers/client/languages/en.ts [hunk 4]
```diff
@@ -199,187 +202,187 @@
...
         <location filename="../QMLLoginView/LoginView/src/LoginViewModule/LoginView.qml" line="248"/>
         <source>SignUp</source>
-        <translation type="unfinished"></translation>
+        <translation>SignUp</translation>
     </message>
     <message>
         <location filename="../QMLLoginView/LoginView/src/LoginViewModule/LoginView.qml" line="281"/>
         <source>Login In</source>
-        <translation type="unfinished"></translation>
+        <translation>Login In</translation>
```
Comment (EndrII) [inline HanoiTowers/client/languages/en.ts:309]: Login In >> LogIn

File: HanoiTowers/client/languages/en.ts [hunk 5]
```diff
@@ -199,187 +202,187 @@
...
     </message>
     <message>
         <location filename="../QMLLoginView/LoginView/src/LoginViewModule/LoginView.qml" line="284"/>
         <source>Sign Up</source>
-        <translation type="unfinished"></translation>
+        <translation>Sign Up</translation>
```
Comment (EndrII) [inline HanoiTowers/client/languages/en.ts:314]: remove space between Sign and Up

File: HanoiTowers/client/languages/ja.ts [hunk 6]
```diff
@@ -29,62 +29,62 @@
...
         <location filename="../backEnd.cpp" line="296"/>
         <source>Failed to create a new user, The name %0 alredy used.</source>
-        <translation type="unfinished"></translation>
+        <translation>新しいユーザーの作成に失敗しました。名前 %0 はすでに使用されています。</translation>
     </message>
     <message>
         <location filename="../backEnd.cpp" line="327"/>
         <source>current profile not online!</source>
-        <translation type="unfinished"></translation>
+        <translation>現在のプロファイルはオンライン！</translation>
```
Comment (EndrII) [inline HanoiTowers/client/languages/ja.ts:82]: 現在のプロファイルはオフラインです！

**Review by EndrII — CHANGES_REQUESTED** [review]
Fix please English and anther languages translations

File: HanoiTowers/client/languages/ja.ts [hunk 7]
```diff
@@ -227,9 +227,9 @@
         <location filename="../Help.qml" line="48"/>
         <source>Your task is to transfer discs of different sizesfrom the left tower to third tower.You can only transfer the top drive of the tower.You can not transfer several disks at once and put larger disks on small disks.</source>
         <translation variants="yes">
-            <lengthvariant>あなたの仕事は左の塔から三番目の塔へ異なるサイズのディスクを移すことです。あなたは塔の一番上のドライブだけを移すことができます。あなたは一度に数枚のディスクを移すことはできません。</lengthvariant>
-            <lengthvariant>あなたの仕事は左の塔から三番目の塔へ異なるサイズのディスクを移すことです。あなたは塔の一番上のドライブだけを移すことができます。あなたは一度に数枚のディスクを移すことはできません。</lengthvariant>
-            <lengthvariant>あなたの仕事は左の塔から三番目の塔へ異なるサイズのディスクを移すことです。あなたは塔の一番上のドライブだけを移すことができます。あなたは一度に数枚のディスクを移すことはできません。</lengthvariant>
+            <lengthvariant>あなたの仕事は、異なるサイズのディスクを左側のタワーから3番目のタワーに移すことです。タワーの一番上のドライブのみを転送できます。一度に複数のディスクを転送して、小さなディスクに大きなディスクを配置することはできません。</lengthvariant>
```
Comment (EndrII) [inline HanoiTowers/client/languages/ja.ts:230]: Disable variants translation

**Review by EndrII — CHANGES_REQUESTED** [review]

**Review by EndrII — APPROVED** [review]
